//
//  ID3v1GenreList.swift
//  Metatron
//
//  Copyright (c) 2016 Almaz Ibragimov
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
//  THE SOFTWARE.
//

import Foundation

public let ID3v1GenreList = ["Blues",
							 "Classic Rock",
							 "Country",
							 "Dance",
							 "Disco",
							 "Funk",
							 "Grunge",
							 "Hip-Hop",
							 "Jazz",
							 "Metal",
							 "New Age",
							 "Oldies",
							 "Other",
							 "Pop",
							 "R&B",
							 "Rap",
							 "Reggae",
							 "Rock",
							 "Techno",
							 "Industrial",
							 "Alternative",
							 "Ska",
							 "Death Metal",
							 "Pranks",
							 "Soundtrack",
							 "Euro-Techno",
							 "Ambient",
							 "Trip-Hop",
							 "Vocal",
							 "Jazz+Funk",
							 "Fusion",
							 "Trance",
							 "Classical",
							 "Instrumental",
							 "Acid",
							 "House",
							 "Game",
							 "Sound Clip",
							 "Gospel",
							 "Noise",
							 "Alternative Rock",
							 "Bass",
							 "Soul",
							 "Punk",
							 "Space",
							 "Meditative",
							 "Instrumental Pop",
							 "Instrumental Rock",
							 "Ethnic",
							 "Gothic",
							 "Darkwave",
							 "Techno-Industrial",
							 "Electronic",
							 "Pop-Folk",
							 "Eurodance",
							 "Dream",
							 "Southern Rock",
							 "Comedy",
							 "Cult",
							 "Gangsta",
							 "Top 40",
							 "Christian Rap",
							 "Pop/Funk",
							 "Jungle",
							 "Native American",
							 "Cabaret",
							 "New Wave",
							 "Psychedelic",
							 "Rave",
							 "Showtunes",
							 "Trailer",
							 "Lo-Fi",
							 "Tribal",
							 "Acid Punk",
							 "Acid Jazz",
							 "Polka",
							 "Retro",
							 "Musical",
							 "Rock & Roll",
							 "Hard Rock",

							 "Folk",
							 "Folk/Rock",
							 "National Folk",
							 "Swing",
							 "Fusion",
							 "Bebob",
							 "Latin",
							 "Revival",
							 "Celtic",
							 "Bluegrass",
							 "Avantgarde",
							 "Gothic Rock",
							 "Progressive Rock",
							 "Psychedelic Rock",
							 "Symphonic Rock",
							 "Slow Rock",
							 "Big Band",
							 "Chorus",
							 "Easy Listening",
							 "Acoustic",
							 "Humour",
							 "Speech",
							 "Chanson",
							 "Opera",
							 "Chamber Music",
							 "Sonata",
							 "Symphony",
							 "Booty Bass",
							 "Primus",
							 "Porn Groove",
							 "Satire",
							 "Slow Jam",
							 "Club",
							 "Tango",
							 "Samba",
							 "Folklore",
							 "Ballad",
							 "Power Ballad",
							 "Rhythmic Soul",
							 "Freestyle",
							 "Duet",
							 "Punk Rock",
							 "Drum Solo",
							 "A Cappella",
							 "Euro-House",
							 "Dance Hall",

							 "Goa",
							 "Drum & Bass",
							 "Club-House",
							 "Hardcore",
							 "Terror",
							 "Indie",
							 "BritPop",
							 "Negerpunk",
							 "Polsk Punk",
							 "Beat",
							 "Christian Gangsta Rap",
							 "Heavy Metal",
							 "Black Metal",
							 "Crossover",
							 "Contemporary Christian",
							 "Christian Rock",
							 "Merengue",
							 "Salsa",
							 "Thrash Metal",
							 "Anime",
							 "Jpop",
							 "Synthpop",
							 "Abstract",
							 "Art Rock",
							 "Baroque",
							 "Bhangra",
							 "Big Beat",
							 "Breakbeat",
							 "Chillout",
							 "Downtempo",
							 "Dub",
							 "EBM",
							 "Eclectic",
							 "Electro",
							 "Electroclash",
							 "Emo",
							 "Experimental",
							 "Garage",
							 "Global",
							 "IDM",
							 "Illbient",
							 "Industro-Goth",
							 "Jam Band",
							 "Krautrock",
							 "Leftfield",
							 "Lounge",
							 "Math Rock",
							 "New Romantic",
							 "Nu-Breakz",
							 "Post-Punk",
							 "Post-Rock",
							 "Psytrance",
							 "Shoegaze",
							 "Space Rock",
							 "Trop Rock",
							 "World Music",
							 "Neoclassical",
							 "Audiobook",
							 "Audio Theatre",
							 "Neue Deutsche Welle",
							 "Podcast",
							 "Indie Rock",
							 "G-Funk",
							 "Dubstep",
							 "Garage Rock",
							 "Psybient"]
